[package]
name = "script-runner"
version = "1.0.0"
edition = "2021"

[dependencies]
rhai = { version = "1.17", features = ["serde"] }
database = { path = "../database" }
cleaner = { path = "../cleaner" }
